# Generated by Django 4.2.16 on 2024-11-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_room_description_alter_room_id_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
