# Generated by Django 4.2.16 on 2024-11-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_menuitem_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.TextField(blank=True),
        ),
    ]
