# Generated by Django 4.2.16 on 2024-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_payment_reservation_payment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('order_not_served', 'Order Not Served'), ('pending', 'Pending'), ('ready', 'Ready')], default='order_not_served', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_kitchen', 'Sent to Kitchen'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
