# Generated by Django 4.2.16 on 2024-11-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_order_status_alter_payment_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='guast_name',
        ),
    ]
